export const countries = [
  { countryName: "Argentina", abbv: "ar" },
  { countryName: "Greece", abbv: "gr" },
  { countryName: "Netherlands", abbv: "nl" },
  { countryName: "South Africa", abbv: "za" },
  { countryName: "Australia", abbv: "au" },
  { countryName: "Honk Kong", abbv: "hk" },
  { countryName: "New Zealand", abbv: "nz" },
  { countryName: "South Korea", abbv: "kr" },
  { countryName: "Austria", abbv: "at" },
  { countryName: "Hungary", abbv: "hu" },
  { countryName: "Nigeria", abbv: "ng" },
  { countryName: "Sweden", abbv: "se" },
  { countryName: "Belgium", abbv: "be" },
  { countryName: "India", abbv: "in" },
  { countryName: "Norway", abbv: "no" },
  { countryName: "Switzerland", abbv: "ch" },
  { countryName: "Brazli", abbv: "br" },
  { countryName: "Indonesia", abbv: "id" },
  { countryName: "Philippines", abbv: "ph" },
  { countryName: "Taiwan", abbv: "tw" },
  { countryName: "Bulagria", abbv: "bg" },
  { countryName: "Ireland", abbv: "ir" },
  { countryName: "Poland", abbv: "pl" },
  { countryName: "Thailand", abbv: "th" },
  { countryName: "Canada", abbv: "ca" },
  { countryName: "Israel", abbv: "il" },
  { countryName: "Portugal", abbv: "pt" },
  { countryName: "Turkey", abbv: "tr" },
  { countryName: "China", abbv: "cn" },
  { countryName: "Italy", abbv: "it" },
  { countryName: "Romania", abbv: "ro" },
  { countryName: "UAE", abbv: "ae" },
  { countryName: "Colombia", abbv: "co" },
  { countryName: "Japan", abbv: "jp" },
  { countryName: "Russia", abbv: "ru" },
  { countryName: "Ukraine", abbv: "ua" },
  { countryName: "Cuba", abbv: "cu" },
  { countryName: "Lativa", abbv: "lv" },
  { countryName: "Saudi Arabia", abbv: "sa" },
  { countryName: "United Kingdom", abbv: "uk" },
  { countryName: "Czech Republic", abbv: "cz" },
  { countryName: "Lithuania", abbv: "lt" },
  { countryName: "Serbia", abbv: "rs" },
  { countryName: "United States", abbv: "us" },
  { countryName: "Egypt", abbv: "eg" },
  { countryName: "Malaysia", abbv: "my" },
  { countryName: "Singapore", abbv: "sg" },
  { countryName: "Venuzuela", abbv: "ve" },
  { countryName: "France", abbv: "fr" },
  { countryName: "Mexico", abbv: "mx" },
  { countryName: "Slovakia", abbv: "sk" },
  { countryName: "Germany", abbv: "de" },
  { countryName: "Marocco", abbv: "ma" },
  { countryName: "Slovenia", abbv: "si"},


];
